# Generated by Django 6.0.6 on 2026-06-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=1024, unique=True)),
                ('documento_id', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROCESADO', 'Convertido a PDF editable y subido al backend'), ('OMITIDO', 'No requería conversión (ya es PDF/DOCX/XLSX editable)'), ('ERROR', 'Ocurrió un error al procesar el archivo')], max_length=20)),
                ('detalle', models.TextField(blank=True, default='')),
                ('archivo_resultado_id', models.BigIntegerField(blank=True, null=True)),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivos_procesados',
                'ordering': ['-fecha_procesado'],
            },
        ),
    ]
